### ISSUE TITLE
NoClassDefFoundError on some PDF files

### ISSUE THREAD

**Issue by dzavodnikov** [dzavodnikov/PdfBookmarksModifier#6]
On some PDF files we are get following exception:

    Exception in thread "main" java.lang.NoClassDefFoundError: org/bouncycastle/asn1/ASN1Encodable
            at com.itextpdf.text.pdf.PdfEncryption.<init>(PdfEncryption.java:148)
            at com.itextpdf.text.pdf.PdfReader.readDecryptedDocObj(PdfReader.java:1024)
            at com.itextpdf.text.pdf.PdfReader.readDocObj(PdfReader.java:1430)
            at com.itextpdf.text.pdf.PdfReader.readPdf(PdfReader.java:732)
            at com.itextpdf.text.pdf.PdfReader.<init>(PdfReader.java:181)
            at com.itextpdf.text.pdf.PdfReader.<init>(PdfReader.java:219)
            at com.itextpdf.text.pdf.PdfReader.<init>(PdfReader.java:207)
            at com.itextpdf.text.pdf.PdfReader.<init>(PdfReader.java:197)
            at org.pdfbookmarksmodifier.IOHelper.updateBookmarks(IOHelper.java:128)
            at org.pdfbookmarksmodifier.CLI.main(CLI.java:80)
    Caused by: java.lang.ClassNotFoundException: org.bouncycastle.asn1.ASN1Encodable
            at java.net.URLClassLoader.findClass(Unknown Source)
            at java.lang.ClassLoader.loadClass(Unknown Source)
            at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
            at java.lang.ClassLoader.loadClass(Unknown Source)
            ... 10 more

**Comment by dzavodnikov** [comment]
Add following dependencies to main JAR-file:
* `compile 'org.bouncycastle:bcpkix-jdk15on:1.54'`
* `compile 'org.bouncycastle:bcprov-ext-jdk15on:1.54'` (optional?)
* `compile 'org.bouncycastle:bcprov-jdk15on:1.54'`

**Comment by dzavodnikov** [comment]
Happens only on protected PDF files.
